name: "Build x2 kernel on github."              # Description of the workflow.
on:
  push:
    branches: darky                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build x2 kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: osm0sis/AnyKernel3                # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                                    # Specify arch
        compiler: proton-clang/master/binutils                         # Specify toolchain to use
        defconfig: lineage_x2_defconfig                                # Specify defconfig to use
        image: Image.gz-dtb                                            # Specify final build file
